[versions]
android-desugar-jdk-libs = "2.1.5"
agp = "9.0.0"
kotlin = "2.3.0"
ksp = "2.3.5"
coroutine = "1.10.2"
coreKtx = "1.17.0"
activity = "1.12.3"
fragment = "1.8.9"
appcompat = "1.7.1"
coordinator = "1.3.0"
okhttp = "5.3.2"
recyclerview = "1.4.0"
viewpager = "1.1.0"
material = "1.13.0"
serialization = "1.10.0"
kaidl = "1.15"
room = "2.8.4"
multiprocess = "1.0.0"
spotless = "8.2.1"
quickie = "1.11.0"

[libraries]
android-desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-desugar-jdk-libs" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutine = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-coordinator = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinator" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-viewpager = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kaidl-compiler = { group = "com.github.kr328.kaidl", name = "kaidl", version.ref = "kaidl" }
kaidl-runtime = { group = "com.github.kr328.kaidl", name = "kaidl-runtime", version.ref = "kaidl" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
rikkax-multiprocess = { group = "dev.rikka.rikkax.preference", name = "multiprocess", version.ref = "multiprocess" }
quickie-bundled = { group = "io.github.g00fy2.quickie", name = "quickie-bundled", version.ref = "quickie" }
gradle-plugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle-plugin-spotless = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }
gradle-plugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-plugin-ksp = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
legacy-kapt = { id = "com.android.legacy-kapt", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
